"""Generate the included-studies appendix (SEGRESS item 17 / Reviewer 2 M11).

Source of truth: results/auxiliary/qa_combined_404_dedup.csv (340 distinct studies)
joined with extraction_combined_404_dedup.csv (IC fields) and FT screening (authors).

Usage:
    python -m pipeline.generate_included_appendix
"""
from __future__ import annotations

import html
import logging
import re
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

ROOT = Path(".")
QA = Path("results/auxiliary/qa_combined_404_dedup.csv")
EXT = Path("results/auxiliary/extraction_combined_404_dedup.csv")
FT = Path("results/screening/ft_screening_results.csv")
CSV_OUT = Path("results/final_review/included_studies_340.csv")
TEX_OUTS = [
    Path("article_ist/overleaf_package/results/included_studies_appendix.tex"),
    Path("results/final_review/included_studies_appendix.tex"),
]


def _tex_escape(s) -> str:
    if s is None or (isinstance(s, float) and pd.isna(s)):
        return "---"
    text = html.unescape(str(s))
    text = text.replace("\xa0", " ").replace("\u2009", " ")
    text = (text.replace("\u201c", '"').replace("\u201d", '"')
                .replace("\u2018", "'").replace("\u2019", "'")
                .replace("\u2013", "-").replace("\u2014", "-")
                .replace("\u00ab", '"').replace("\u00bb", '"'))
    text = re.sub(r"\s+", " ", text).strip()
    repl = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]
    for a, b in repl:
        text = text.replace(a, b)
    return text


def _norm_doi(s) -> str:
    if pd.isna(s):
        return ""
    s = str(s).strip()
    s = re.sub(r"^https?://(dx\.)?doi\.org/", "", s, flags=re.I)
    return s.strip()


def _origin_label(v) -> str:
    if pd.isna(v) or str(v).strip() == "":
        return "Aux2"
    v = str(v).strip().lower()
    if v == "working_set":
        return "WS"
    if v == "auxiliary":
        return "Aux1"
    return v


def _year(v) -> str:
    if pd.isna(v):
        return "---"
    try:
        return str(int(float(v)))
    except (TypeError, ValueError):
        return str(v)[:4]


def _authors_short(s) -> str:
    if pd.isna(s) or not str(s).strip():
        return ""
    raw = str(s).strip()
    # keep first author + et al. if multiple
    parts = re.split(r";|, and | and ", raw)
    first = parts[0].strip().rstrip(",")
    if len(parts) > 1 or ";" in raw:
        return first + " et al."
    return first


def build() -> pd.DataFrame:
    qa = pd.read_csv(QA)
    ext = pd.read_csv(EXT)
    keep_ext = ext[["internal_id", "ft_matched_ic", "source_db"]].drop_duplicates("internal_id")
    df = qa.merge(keep_ext, on="internal_id", how="left")

    by_id, by_doi = {}, {}
    if FT.exists():
        ft = pd.read_csv(FT, usecols=lambda c: c in {"internal_id", "authors", "venue", "doi"},
                         low_memory=False)
        for _, row in ft.iterrows():
            a = row.get("authors")
            if pd.isna(a) or not str(a).strip():
                continue
            a = str(a).strip()
            iid = str(row.get("internal_id", "")).strip()
            if iid and iid not in by_id:
                by_id[iid] = a
            d = _norm_doi(row.get("doi"))
            if d and d not in by_doi:
                by_doi[d] = a

    df["doi_n"] = df["doi"].map(_norm_doi)
    df["authors"] = [
        by_id.get(str(i), "") or by_doi.get(d, "")
        for i, d in zip(df["internal_id"], df["doi_n"])
    ]
    df["origin_label"] = df["origin"].map(_origin_label)
    df["year_s"] = df["year"].map(_year)
    df["qa_n"] = pd.to_numeric(df["qa_total"], errors="coerce")
    df = df.sort_values(["year_s", "title"], kind="mergesort").reset_index(drop=True)
    df.insert(0, "seq", range(1, len(df) + 1))
    return df


def write_csv(df: pd.DataFrame) -> None:
    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    out = df[["seq", "internal_id", "year_s", "authors", "title", "doi_n",
              "origin_label", "source_db", "ft_matched_ic", "qa_n", "qa_include"]].copy()
    out.columns = ["seq", "internal_id", "year", "authors", "title", "doi",
                   "origin", "source_db", "ic", "qa_total", "qa_include"]
    out.to_csv(CSV_OUT, index=False)
    logger.info("Wrote %s (%d rows)", CSV_OUT, len(out))


def write_tex(df: pd.DataFrame) -> None:
    n = len(df)
    n_doi = int((df["doi_n"] != "").sum())
    lines = [
        r"% Auto-generated by pipeline/generate_included_appendix.py --- do not edit by hand.",
        r"\begingroup\small",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{longtable}{r c p{1.55cm} p{6.55cm} p{2.85cm} l c r}",
        rf"\caption{{Confirmed primary studies after cross-tier deduplication "
        rf"($N={n}$; {n_doi} with a DOI). Column \texttt{{ID}} is the "
        rf"\texttt{{internal\_id}} key used in the extraction and QA sheets of the "
        rf"replication package. Origin: WS~=~working-set tier; Aux1~=~first auxiliary "
        rf"pass; Aux2~=~second auxiliary pass. QA is the Dyb{{\aa}} and Dings{{\o}}yr "
        rf"reporting-quality total (0--8).}}",
        r"\label{tab:included-studies}\\",
        r"\toprule",
        r"\# & Year & Authors & Title & DOI / ID & Origin & IC & QA \\",
        r"\midrule",
        r"\endfirsthead",
        rf"\multicolumn{{8}}{{c}}{{\tablename\ \thetable{{}} --- continued from previous page}}\\",
        r"\toprule",
        r"\# & Year & Authors & Title & DOI / ID & Origin & IC & QA \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        rf"\multicolumn{{8}}{{r}}{{\emph{{Continued on next page}}}}\\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for _, row in df.iterrows():
        seq = int(row["seq"])
        year = _tex_escape(row["year_s"])
        auth = _tex_escape(_authors_short(row["authors"])) or "---"
        title = _tex_escape(row["title"])
        iid = str(row["internal_id"])
        doi = row["doi_n"]
        if doi:
            doi_cell = rf"\href{{https://doi.org/{doi}}}{{\texttt{{{_tex_escape(doi)}}}}}"
        else:
            doi_cell = rf"\texttt{{{_tex_escape(iid)}}}"
        origin = _tex_escape(row["origin_label"])
        ic = _tex_escape(row["ft_matched_ic"] if pd.notna(row.get("ft_matched_ic")) else "")
        if ic == "---" or ic == "":
            ic = "---"
        qa = "---" if pd.isna(row["qa_n"]) else f"{int(row['qa_n'])}"
        lines.append(
            f"{seq} & {year} & {auth} & {title} & {doi_cell} & {origin} & {ic} & {qa} \\\\"
        )
    lines += [
        r"\end{longtable}",
        r"\endgroup",
        "",
        r"\noindent\textit{Notes.} "
        r"Studies without a recoverable DOI are keyed by \texttt{internal\_id} only. "
        r"Author strings are taken from the working-set full-text screening metadata "
        r"when available (first author + et~al.); auxiliary-tier rows may show "
        r"``---'' because that tier was screened from title/abstract metadata. "
        r"Full bibliographic records and extraction fields are in "
        r"\texttt{results/auxiliary/extraction\_combined\_404\_dedup.csv}.",
    ]
    body = "\n".join(lines) + "\n"
    for path in TEX_OUTS:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body, encoding="utf-8")
        logger.info("Wrote %s", path)


def main() -> None:
    df = build()
    assert len(df) == 340, f"expected 340 distinct studies, got {len(df)}"
    write_csv(df)
    write_tex(df)
    n_doi = int((df["doi_n"] != "").sum())
    n_auth = int((df["authors"] != "").sum())
    print(f"Included-studies appendix: n={len(df)}  DOI={n_doi}  authors={n_auth}")


if __name__ == "__main__":
    main()
