"""
10 control papers (validation set) para a SLR PATHCAST.
Threshold: >= 8/10 capturados pelas strings de busca.
"""

CONTROL_PAPERS = [
    {
        "id": "V1",
        "citation": "Cook & Wolf (1998)",
        "title": "Discovering Models of Software Processes from Event-Based Data",
        "authors": ["Cook, Jonathan E.", "Wolf, Alexander L."],
        "year": 1998,
        "doi": "10.1145/295558.295563",
        "venue": "ACM Transactions on Software Engineering and Methodology",
        "expected_string": "Principal",
        "note": "Marco zero PM + SE",
    },
    {
        "id": "V2",
        "citation": "Rubin et al. (2007)",
        "title": "Process Mining Framework for Software Processes",
        "authors": ["Rubin, Vladimir", "Günther, Christian W.", "van der Aalst, Wil M. P.", "Kindler, Ekkart"],
        "year": 2007,
        "doi": "10.1007/978-3-540-72426-1_14",
        "venue": "International Conference on Software Process",
        "expected_string": "Principal",
        "note": "Framework PM para processos de SW",
    },
    {
        "id": "V3",
        "citation": "Poncin et al. (2011)",
        "title": "Process Mining Software Repositories",
        "authors": ["Poncin, Wouter", "Serebrenik, Alexander", "van den Brand, Mark"],
        "year": 2011,
        "doi": "10.1109/CSMR.2011.5",
        "venue": "European Conference on Software Maintenance and Reengineering",
        "expected_string": "Principal",
        "note": "Intersecção direta PM + MSR",
    },
    {
        "id": "V4",
        "citation": "Caldeira & Cardoso (2019)",
        "title": "Assessing Software Development Teams' Efficiency using Process Mining",
        "authors": [
            "Caldeira, João",
            "Brito e Abreu, Fernando",
            "Reis, José",
            "Cardoso, Jorge",
        ],
        "year": 2019,
        "doi": "10.1109/ICPM.2019.00020",
        "venue": "International Conference on Process Mining",
        "expected_string": "Principal",
        "note": "PM + assessment de processos de SW",
    },
    {
        "id": "V5",
        "citation": "Lemos et al. (2011)",
        "title": "Using Process Mining in Software Development Process Management",
        "authors": ["Lemos, Otávio A. L.", "César, Lucas", "Zanetti, Diogo", "Dias Canedo, Edna"],
        "year": 2011,
        "doi": None,
        "venue": "International Conference on Software Engineering and Knowledge Engineering",
        "expected_string": "Principal",
        "note": "PM para gestão de processos de SW",
    },
    {
        "id": "V6",
        "citation": "Whittaker & Thomason (1994)",
        "title": "A Markov Chain Model for Statistical Software Testing",
        "authors": ["Whittaker, James A.", "Thomason, Michael G."],
        "year": 1994,
        "doi": "10.1109/32.328991",
        "venue": "IEEE Transactions on Software Engineering",
        "expected_string": "Complementar/Snowball",
        "note": "Markov + Software (seminal); pode entrar via snowballing",
    },
    {
        "id": "V7",
        "citation": "Tax et al. (2017)",
        "title": "Predictive Business Process Monitoring with LSTM Neural Networks",
        "authors": ["Tax, Niek", "Verenich, Ilya", "La Rosa, Marcello", "Dumas, Marlon"],
        "year": 2017,
        "doi": "10.1007/978-3-319-59536-8_30",
        "venue": "International Conference on Advanced Information Systems Engineering",
        "expected_string": "Principal",
        "note": "PPM seminal (baseline BPM genérico)",
    },
    {
        "id": "V8",
        "citation": "Rogge-Solti & Weske (2015)",
        "title": "Prediction of Remaining Service Execution Time Using Stochastic Petri Nets with Arbitrary Firing Delays",
        "authors": ["Rogge-Solti, Andreas", "Weske, Mathias"],
        "year": 2013,
        "doi": "10.1007/978-3-642-45005-1_27",
        "venue": "ICSOC 2013 / Service-Oriented Computing Workshops",
        "expected_string": "Principal/Fronteira",
        "note": "Versão de controle alinhada ao PDF local baixado",
    },
    {
        "id": "V9",
        "citation": "Rozinat et al. (2009)",
        "title": "Discovering Simulation Models",
        "authors": ["Rozinat, A.", "Mans, R. S.", "Song, M.", "van der Aalst, Wil M. P."],
        "year": 2007,
        "doi": None,
        "venue": "BETA Working Paper 223, Technische Universiteit Eindhoven",
        "expected_string": "Principal",
        "note": "Versão de controle alinhada ao PDF local baixado",
    },
    {
        "id": "V10",
        "citation": "Gupta & Sureka (2017)",
        "title": "Process Mining Multiple Repositories for Software Defect Resolution from Control and Organizational Perspective",
        "authors": ["Gupta, Monika", "Sureka, Ashish", "Padmanabhuni, Srinivas"],
        "year": 2014,
        "doi": "10.1145/2597073.2597081",
        "venue": "MSR 2014",
        "expected_string": "Principal",
        "note": "Versão de controle alinhada ao PDF local baixado",
    },
]
